#############################################################################
# Makefile for building: Flocker
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Flocker.pro
# Template: app
# Command: /Users/Vijin/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Flocker.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT5BUILD -DQT5BUILD -DNGL_DEBUG -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -msse -msse2 -msse3 -arch x86_64 -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -Wno-unused-parameter -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -isystem /usr/local/include -I/Users/Vijin/NGL/include -I/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Vijin/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/Vijin/Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/Vijin/Qt/5.7/clang_64/lib
QMAKE         = /Users/Vijin/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Flocker1.0.0
DISTDIR = /Users/Vijin/ASE/Project/Flocker_live/.tmp/Flocker1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,@loader_path/L/Users/Vijin/NGL/lib -Wl,-rpath,/Users/Vijin/NGL/lib -Wl,-rpath,/Users/Vijin/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Vijin/Qt/5.7/clang_64/lib -L/usr/local/lib -L/Users/Vijin/NGL/lib -l NGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Boid.cpp \
		src/Openglwidget.cpp \
		src/MainWindow.cpp \
		src/World.cpp \
		src/Octree.cpp \
		src/Obstacle.cpp moc_Openglwidget.cpp \
		moc_MainWindow.cpp
OBJECTS       = main.o \
		Boid.o \
		Openglwidget.o \
		MainWindow.o \
		World.o \
		Octree.o \
		Obstacle.o \
		moc_Openglwidget.o \
		moc_MainWindow.o
DIST          = .qmake.stash \
		Flocker.pro include/Boid.h \
		include/WindowParams.h \
		include/Openglwidget.h \
		include/MainWindow.h \
		include/World.h \
		include/Octree.h \
		include/OctreePoint.h \
		include/Obstacle.h src/main.cpp \
		src/Boid.cpp \
		src/Openglwidget.cpp \
		src/MainWindow.cpp \
		src/World.cpp \
		src/Octree.cpp \
		src/Obstacle.cpp
QMAKE_TARGET  = Flocker
DESTDIR       = 
TARGET        = Flocker


first: all
####### Build rules

$(TARGET): ui_MainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Flocker.pro .qmake.cache /Users/Vijin/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf /Users/Vijin/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/qdevice.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/unix.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/mac.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/macx.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/clang.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/qconfig.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Vijin/NGL/UseNGL.pri \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qt.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/resources.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/moc.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/uic.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Flocker.pro \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Flocker.pro
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/qdevice.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/device_config.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/unix.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/mac.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/macx.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/clang.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/qconfig.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Vijin/NGL/UseNGL.pri:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/default_post.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/qt.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/resources.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/moc.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/uic.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/yacc.prf:
/Users/Vijin/Qt/5.7/clang_64/mkspecs/features/lex.prf:
Flocker.pro:
/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Vijin/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Flocker.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/Boid.h include/WindowParams.h include/Openglwidget.h include/MainWindow.h include/World.h include/Octree.h include/OctreePoint.h include/Obstacle.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Boid.cpp src/Openglwidget.cpp src/MainWindow.cpp src/World.cpp src/Octree.cpp src/Obstacle.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/MainWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Openglwidget.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Openglwidget.cpp moc_MainWindow.cpp
moc_Openglwidget.cpp: /Users/Vijin/NGL/include/ngl/Camera.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Mat4.h \
		/Users/Vijin/NGL/include/ngl/RibExport.h \
		/Users/Vijin/NGL/include/ngl/Plane.h \
		/Users/Vijin/NGL/include/ngl/AABB.h \
		/Users/Vijin/NGL/include/ngl/BBox.h \
		/Users/Vijin/NGL/include/ngl/AbstractVAO.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Light.h \
		/Users/Vijin/NGL/include/ngl/Text.h \
		/Users/Vijin/NGL/include/ngl/VAOFactory.h \
		/Users/Vijin/NGL/include/ngl/SimpleVAO.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		/Users/Vijin/NGL/include/ngl/VAOPrimitives.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h \
		/Users/Vijin/NGL/include/ngl/Transformation.h \
		/Users/Vijin/NGL/include/ngl/NGLassert.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/WindowParams.h \
		include/World.h \
		include/Boid.h \
		include/Octree.h \
		include/OctreePoint.h \
		include/Obstacle.h \
		include/Openglwidget.h \
		/Users/Vijin/Qt/5.7/clang_64/bin/moc
	/Users/Vijin/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Vijin/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Vijin/ASE/Project/Flocker_live -I/Users/Vijin/ASE/Project/Flocker_live/include -I/usr/local/include -I/Users/Vijin/NGL/include -I/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Vijin/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/Vijin/Qt/5.7/clang_64/lib include/Openglwidget.h -o moc_Openglwidget.cpp

moc_MainWindow.cpp: /Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		include/Openglwidget.h \
		/Users/Vijin/NGL/include/ngl/Camera.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Mat4.h \
		/Users/Vijin/NGL/include/ngl/RibExport.h \
		/Users/Vijin/NGL/include/ngl/Plane.h \
		/Users/Vijin/NGL/include/ngl/AABB.h \
		/Users/Vijin/NGL/include/ngl/BBox.h \
		/Users/Vijin/NGL/include/ngl/AbstractVAO.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Light.h \
		/Users/Vijin/NGL/include/ngl/Text.h \
		/Users/Vijin/NGL/include/ngl/VAOFactory.h \
		/Users/Vijin/NGL/include/ngl/SimpleVAO.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		/Users/Vijin/NGL/include/ngl/VAOPrimitives.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h \
		/Users/Vijin/NGL/include/ngl/Transformation.h \
		/Users/Vijin/NGL/include/ngl/NGLassert.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/WindowParams.h \
		include/World.h \
		include/Boid.h \
		include/Octree.h \
		include/OctreePoint.h \
		include/Obstacle.h \
		include/MainWindow.h \
		/Users/Vijin/Qt/5.7/clang_64/bin/moc
	/Users/Vijin/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Vijin/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Vijin/ASE/Project/Flocker_live -I/Users/Vijin/ASE/Project/Flocker_live/include -I/usr/local/include -I/Users/Vijin/NGL/include -I/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Vijin/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/Vijin/Qt/5.7/clang_64/lib include/MainWindow.h -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h
ui_MainWindow.h: ui/MainWindow.ui \
		/Users/Vijin/Qt/5.7/clang_64/bin/uic
	/Users/Vijin/Qt/5.7/clang_64/bin/uic ui/MainWindow.ui -o ui_MainWindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp include/MainWindow.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		include/Openglwidget.h \
		/Users/Vijin/NGL/include/ngl/Camera.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Mat4.h \
		/Users/Vijin/NGL/include/ngl/RibExport.h \
		/Users/Vijin/NGL/include/ngl/Plane.h \
		/Users/Vijin/NGL/include/ngl/AABB.h \
		/Users/Vijin/NGL/include/ngl/BBox.h \
		/Users/Vijin/NGL/include/ngl/AbstractVAO.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Light.h \
		/Users/Vijin/NGL/include/ngl/Text.h \
		/Users/Vijin/NGL/include/ngl/VAOFactory.h \
		/Users/Vijin/NGL/include/ngl/SimpleVAO.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		/Users/Vijin/NGL/include/ngl/VAOPrimitives.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h \
		/Users/Vijin/NGL/include/ngl/Transformation.h \
		/Users/Vijin/NGL/include/ngl/NGLassert.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/WindowParams.h \
		include/World.h \
		include/Boid.h \
		include/Octree.h \
		include/OctreePoint.h \
		include/Obstacle.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Boid.o: src/Boid.cpp include/Boid.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Random.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Boid.o src/Boid.cpp

Openglwidget.o: src/Openglwidget.cpp /Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		include/Openglwidget.h \
		/Users/Vijin/NGL/include/ngl/Camera.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Mat4.h \
		/Users/Vijin/NGL/include/ngl/RibExport.h \
		/Users/Vijin/NGL/include/ngl/Plane.h \
		/Users/Vijin/NGL/include/ngl/AABB.h \
		/Users/Vijin/NGL/include/ngl/BBox.h \
		/Users/Vijin/NGL/include/ngl/AbstractVAO.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Light.h \
		/Users/Vijin/NGL/include/ngl/Text.h \
		/Users/Vijin/NGL/include/ngl/VAOFactory.h \
		/Users/Vijin/NGL/include/ngl/SimpleVAO.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		/Users/Vijin/NGL/include/ngl/VAOPrimitives.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h \
		/Users/Vijin/NGL/include/ngl/Transformation.h \
		/Users/Vijin/NGL/include/ngl/NGLassert.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/WindowParams.h \
		include/World.h \
		include/Boid.h \
		include/Octree.h \
		include/OctreePoint.h \
		include/Obstacle.h \
		/Users/Vijin/NGL/include/ngl/Material.h \
		/Users/Vijin/NGL/include/ngl/NGLInit.h \
		/Users/Vijin/NGL/include/ngl/ShaderLib.h \
		/Users/Vijin/NGL/include/ngl/Shader.h \
		/Users/Vijin/NGL/include/ngl/ShaderProgram.h \
		/Users/Vijin/NGL/include/ngl/Util.h \
		/Users/Vijin/NGL/include/ngl/Mat3.h \
		/Users/Vijin/NGL/include/ngl/Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Openglwidget.o src/Openglwidget.cpp

MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		include/Openglwidget.h \
		/Users/Vijin/NGL/include/ngl/Camera.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Mat4.h \
		/Users/Vijin/NGL/include/ngl/RibExport.h \
		/Users/Vijin/NGL/include/ngl/Plane.h \
		/Users/Vijin/NGL/include/ngl/AABB.h \
		/Users/Vijin/NGL/include/ngl/BBox.h \
		/Users/Vijin/NGL/include/ngl/AbstractVAO.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Light.h \
		/Users/Vijin/NGL/include/ngl/Text.h \
		/Users/Vijin/NGL/include/ngl/VAOFactory.h \
		/Users/Vijin/NGL/include/ngl/SimpleVAO.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/QFont \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		/Users/Vijin/NGL/include/ngl/VAOPrimitives.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h \
		/Users/Vijin/NGL/include/ngl/Transformation.h \
		/Users/Vijin/NGL/include/ngl/NGLassert.h \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/Vijin/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		include/WindowParams.h \
		include/World.h \
		include/Boid.h \
		include/Octree.h \
		include/OctreePoint.h \
		include/Obstacle.h \
		include/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/MainWindow.cpp

World.o: src/World.cpp include/World.h \
		include/Boid.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		include/Octree.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		include/OctreePoint.h \
		include/Obstacle.h \
		/Users/Vijin/NGL/include/ngl/Random.h \
		/Users/Vijin/NGL/include/ngl/Colour.h \
		/Users/Vijin/NGL/include/ngl/Singleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o World.o src/World.cpp

Octree.o: src/Octree.cpp include/Octree.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h \
		/Users/Vijin/NGL/include/ngl/Vec4.h \
		/Users/Vijin/NGL/include/ngl/Vec2.h \
		include/OctreePoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Octree.o src/Octree.cpp

Obstacle.o: src/Obstacle.cpp include/Obstacle.h \
		/Users/Vijin/NGL/include/ngl/Vec3.h \
		/Users/Vijin/NGL/include/ngl/Types.h \
		/Users/Vijin/NGL/include/ngl/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Obstacle.o src/Obstacle.cpp

moc_Openglwidget.o: moc_Openglwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Openglwidget.o moc_Openglwidget.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

